[package]
name = "pasaka"
version = "0.1.0"
edition = "2024"

[dependencies]
console = "0.16.0"
dialoguer = "0.12.0"
erased-serde = "0.4.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
typetag = "0.2.20"

[dev-dependencies]
fastrand = "2.3.0"
smol = "2.0.2"
pasaka_macro = { path = "../pasaka_macro" }
