[package]
name = "pasaka"
version = "0.1.0"
edition = "2024"

[dependencies]
console = "0.16.0"
ctor = "0.5.0"
dialoguer = "0.12.0"
erased-serde = "0.4.6"
inventory = "0.3.21"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
typetag = "0.2.20"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = [
    "Window",
    "Document",
    "Element",
    "Storage",
    "console",
    'HtmlElement',
    'Node',
] }

[dev-dependencies]
fastrand = "2.3.0"
smol = "2.0.2"
