[package]
name = "dungeon"
version = "0.1.0"
edition = "2024"
publish = false
license = "UNLICENSED"

[dependencies]
pasaka = { path = "../../pasaka" }
fastrand = "2.3.0"
serde = { version = "1.0.219", features = ["derive"] }
