[package]
name = "dungeon"
version = "0.1.0"
edition = "2024"

[dependencies]
pasaka = { path = "../../pasaka" }
pasaka_macro = { path = "../../pasaka_macro" }
smol = "2.0.2"
fastrand = "2.3.0"
serde = "1.0.219"
ctor = "0.5.0"
