[package]
name = "hello-web"
version = "0.1.0"
edition = "2024"
publish = false
license = "UNLICENSED"


[dependencies]
pasaka = { version = "0.1.0", path = "../../pasaka", features = ["web"] }
serde = { version = "1.0.219", features = ["derive"] }
